### ISSUE TITLE
Compiling with maven a generated pom with Grails v2.5.0 it does not compile (but it does work with Grails v2.4.5)

### ISSUE THREAD

**Issue by rbatllet** [grails/grails-maven#67]
$ mvn package

[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.twintags:bpmn-webapp:grails-app:1.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 160, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building bpmn-webapp 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- grails-maven-plugin:2.4.4:validate (default-validate) @ bpmn-webapp ---
[INFO] 
[INFO] --- grails-maven-plugin:2.4.4:init (default-init) @ bpmn-webapp ---
[INFO] 
[INFO] --- grails-maven-plugin:2.4.4:config-directories (default-config-directories) @ bpmn-webapp ---
[INFO] 
[INFO] --- grails-maven-plugin:2.4.4:maven-compile (default-maven-compile) @ bpmn-webapp ---
|Loading Grails 2.5.0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.182 s
[INFO] Finished at: 2015-04-22T16:52:26+02:00
[INFO] Final Memory: 23M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.grails:grails-maven-plugin:2.4.4:maven-compile (default-maven-compile) on project bpmn-webapp: Execution default-maven-compile of goal org.grails:grails-maven-plugin:2.4.4:maven-compile failed: java.lang.reflect.InvocationTargetException: org.codehaus.groovy.runtime.DefaultGroovyMethods.each(Ljava/util/Collection;Lgroovy/lang/Closure;)Ljava/util/Collection; -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by Kanishkaz** [comment]
We have noticed the same issue with 2.5.0 and have reverted back to 2.4.4.

**Comment by graemerocher** [comment]
this looks like 2 versions of Groovy on the classpath, can you post the output of `mvn dependency:tree`?

**Comment by rbatllet** [comment]
$ mvn dependency:tree

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.mycompany:test:grails-app:0.1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 160, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[WARNING] The POM for org.apache.maven.plugins:maven-clean-plugin:jar:2.4.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-clean-plugin:2.4.0: Plugin org.apache.maven.plugins:maven-clean-plugin:2.4.0 or one of its dependencies could not be resolved: Failure to find org.apache.maven.plugins:maven-clean-plugin:jar:2.4.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building test 0.1
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.apache.maven.plugins:maven-clean-plugin:jar:2.4.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-clean-plugin:2.4.0: Plugin org.apache.maven.plugins:maven-clean-plugin:2.4.0 or one of its dependencies could not be resolved: Failure to find org.apache.maven.plugins:maven-clean-plugin:jar:2.4.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ test ---
[INFO] org.mycompany:test:grails-app:0.1
[INFO] +- org.grails:grails-dependencies:pom:2.5.0:compile
[INFO] |  +- org.codehaus.groovy:groovy-all:jar:2.4.3:compile
[INFO] |  +- org.grails:grails-plugin-rest:jar:2.5.0:compile
[INFO] |  |  +- org.grails:grails-plugin-datasource:jar:2.5.0:compile
[INFO] |  |  |  +- org.springframework:spring-jdbc:jar:4.1.5.RELEASE:compile
[INFO] |  |  |  +- org.springframework:spring-context:jar:4.1.5.RELEASE:compile
[INFO] |  |  |  |  +- org.springframework:spring-aop:jar:4.1.5.RELEASE:compile
[INFO] |  |  |  |  \- org.springframework:spring-expression:jar:4.1.5.RELEASE:compile
[INFO] |  |  |  \- org.apache.tomcat:tomcat-jdbc:jar:7.0.50:compile
[INFO] |  |  |     \- org.apache.tomcat:tomcat-juli:jar:7.0.50:compile
[INFO] |  |  \- com.google.code.gson:gson:jar:2.2.4:compile
[INFO] |  +- org.grails:grails-plugin-databinding:jar:2.5.0:compile
[INFO] |  |  \- org.grails:grails-core:jar:2.5.0:compile
[INFO] |  |     +- xalan:serializer:jar:2.7.2:runtime
[INFO] |  |     +- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  |     \- org.grails:grails-bootstrap:jar:2.5.0:compile
[INFO] |  +- org.grails:grails-plugin-i18n:jar:2.5.0:compile
[INFO] |  |  \- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  +- org.grails:grails-plugin-filters:jar:2.5.0:compile
[INFO] |  +- org.grails:grails-plugin-gsp:jar:2.5.0:compile
[INFO] |  |  \- org.grails:grails-web-gsp-taglib:jar:2.5.0:compile
[INFO] |  +- org.grails:grails-plugin-log4j:jar:2.5.0:compile
[INFO] |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.5:compile
[INFO] |  +- org.grails:grails-plugin-services:jar:2.5.0:compile
[INFO] |  +- org.grails:grails-plugin-servlets:jar:2.5.0:compile
[INFO] |  +- org.grails:grails-plugin-url-mappings:jar:2.5.0:compile
[INFO] |  |  +- com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar:1.4:compile
[INFO] |  |  \- org.grails:grails-validation:jar:2.5.0:compile
[INFO] |  |     \- commons-validator:commons-validator:jar:1.4.0:compile
[INFO] |  +- org.grails:grails-plugin-async:jar:2.5.0:compile
[INFO] |  |  \- org.grails:grails-async:jar:2.5.0:compile
[INFO] |  |     \- org.codehaus.gpars:gpars:jar:1.2.1:compile
[INFO] |  |        \- org.codehaus.jsr166-mirror:jsr166y:jar:1.7.0:compile
[INFO] |  +- log4j:log4j:jar:1.2.17:compile
[INFO] |  \- org.grails:grails-resources:jar:2.5.0:runtime
[INFO] +- org.grails:grails-test:jar:2.5.0:test
[INFO] |  +- org.springframework:spring-tx:jar:4.1.5.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-beans:jar:4.1.5.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-core:jar:4.1.5.RELEASE:compile
[INFO] |  +- org.grails:grails-plugin-mimetypes:jar:2.5.0:compile
[INFO] |  +- org.slf4j:jcl-over-slf4j:jar:1.7.5:compile
[INFO] |  +- org.grails:grails-project-api:jar:2.5.0:test
[INFO] |  |  +- org.apache.ant:ant:jar:1.8.4:test
[INFO] |  |  |  \- org.apache.ant:ant-launcher:jar:1.8.4:test
[INFO] |  |  +- jline:jline:jar:2.12:test
[INFO] |  |  +- org.codehaus.gant:gant_groovy1.8:jar:1.9.6:test
[INFO] |  |  \- org.fusesource.jansi:jansi:jar:1.11:test
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.5:compile
[INFO] |  +- org.grails:grails-plugin-converters:jar:2.5.0:compile
[INFO] |  +- org.grails:grails-web:jar:2.5.0:compile
[INFO] |  |  +- org.grails:grails-web-jsp:jar:2.5.0:compile
[INFO] |  |  +- org.grails:grails-web-common:jar:2.5.0:compile
[INFO] |  |  |  +- org.springframework:spring-context-support:jar:4.1.5.RELEASE:compile
[INFO] |  |  |  +- org.springframework:spring-webmvc:jar:4.1.5.RELEASE:compile
[INFO] |  |  |  \- org.grails:grails-databinding:jar:2.5.0:compile
[INFO] |  |  +- org.grails:grails-web-url-mappings:jar:2.5.0:compile
[INFO] |  |  +- org.springframework:spring-aspects:jar:4.1.5.RELEASE:runtime
[INFO] |  |  +- org.grails:grails-web-sitemesh:jar:2.5.0:compile
[INFO] |  |  |  \- opensymphony:sitemesh:jar:2.4:compile
[INFO] |  |  +- org.aspectj:aspectjweaver:jar:1.8.5:runtime
[INFO] |  |  +- org.grails:grails-web-fileupload:jar:2.5.0:compile
[INFO] |  |  |  \- commons-fileupload:commons-fileupload:jar:1.3.1:compile
[INFO] |  |  +- org.grails:grails-web-mvc:jar:2.5.0:compile
[INFO] |  |  +- org.grails:grails-web-databinding:jar:2.5.0:compile
[INFO] |  |  +- org.grails:grails-web-gsp:jar:2.5.0:compile
[INFO] |  |  \- org.aspectj:aspectjrt:jar:1.8.5:runtime
[INFO] |  \- org.objenesis:objenesis:jar:1.4:test
[INFO] +- org.grails:grails-plugin-testing:jar:2.5.0:test
[INFO] |  +- org.grails:grails-plugin-codecs:jar:2.5.0:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.6:compile
[INFO] |  |  \- org.grails:grails-encoder:jar:2.5.0:compile
[INFO] |  |     \- org.springframework:spring-web:jar:4.1.5.RELEASE:compile
[INFO] |  +- org.springframework:spring-test:jar:4.1.5.RELEASE:test
[INFO] |  +- org.grails:grails-plugin-controllers:jar:2.5.0:compile
[INFO] |  |  \- org.grails:grails-plugin-validation:jar:2.5.0:compile
[INFO] |  +- cglib:cglib:jar:2.2.2:test
[INFO] |  |  \- asm:asm:jar:3.3.1:test
[INFO] |  +- org.grails:grails-logging:jar:2.5.0:compile
[INFO] |  \- org.grails:grails-plugin-domain-class:jar:2.5.0:compile
[INFO] |     \- org.grails:grails-spring:jar:2.5.0:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.spockframework:spock-core:jar:1.0-groovy-2.4:test
[INFO] +- com.h2database:h2:jar:1.3.170:runtime
[INFO] +- org.grails:grails-datastore-test-support:jar:1.0.2-grails-2.4:test
[INFO] +- org.grails.plugins:scaffolding:zip:2.1.2:compile
[INFO] +- org.grails.plugins:cache:zip:1.1.8:compile
[INFO] |  \- org.javassist:javassist:jar:3.17.1-GA:compile
[INFO] +- org.grails.plugins:asset-pipeline:zip:2.1.5:compile
[INFO] |  +- org.mozilla:rhino:jar:1.7R4:runtime
[INFO] |  +- commons-io:commons-io:jar:2.2:compile
[INFO] |  \- com.bertramlabs.plugins:asset-pipeline-core:jar:2.1.1:compile
[INFO] |     +- com.google.javascript:closure-compiler:jar:v20141023:runtime
[INFO] |     |  +- com.google.javascript:closure-compiler-externs:jar:v20141023:runtime
[INFO] |     |  +- args4j:args4j:jar:2.0.26:runtime
[INFO] |     |  +- com.google.guava:guava:jar:18.0:runtime
[INFO] |     |  +- com.google.protobuf:protobuf-java:jar:2.5.0:runtime
[INFO] |     |  \- com.google.code.findbugs:jsr305:jar:1.3.9:runtime
[INFO] |     \- commons-logging:commons-logging:jar:1.1.1:runtime
[INFO] +- org.grails.plugins:hibernate4:zip:4.3.8.1:runtime
[INFO] |  +- org.hibernate:hibernate-validator:jar:5.1.3.Final:runtime
[INFO] |  |  +- javax.validation:validation-api:jar:1.1.0.Final:runtime
[INFO] |  |  \- com.fasterxml:classmate:jar:1.0.0:runtime
[INFO] |  +- org.hibernate:hibernate-ehcache:jar:4.3.8.Final:runtime
[INFO] |  |  \- org.hibernate:hibernate-core:jar:4.3.8.Final:runtime
[INFO] |  |     +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.0.0.Final:runtime
[INFO] |  |     +- antlr:antlr:jar:2.7.7:runtime
[INFO] |  |     \- org.jboss:jandex:jar:1.1.0.Final:runtime
[INFO] |  +- net.sf.ehcache:ehcache:jar:2.9.0:runtime
[INFO] |  +- org.jboss.logging:jboss-logging:jar:3.1.0.GA:runtime
[INFO] |  +- org.grails:grails-datastore-core:jar:3.1.4.RELEASE:compile
[INFO] |  |  \- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.Final:compile
[INFO] |  +- org.grails:grails-datastore-gorm:jar:3.1.4.RELEASE:compile
[INFO] |  +- org.grails:grails-datastore-gorm-hibernate4:jar:3.1.4.RELEASE:runtime
[INFO] |  |  +- org.hibernate.common:hibernate-commons-annotations:jar:4.0.4.Final:runtime
[INFO] |  |  |  \- org.jboss.logging:jboss-logging-annotations:jar:1.2.0.Beta1:runtime
[INFO] |  |  +- dom4j:dom4j:jar:1.6.1:runtime
[INFO] |  |  \- org.grails:grails-datastore-gorm-hibernate-core:jar:3.1.4.RELEASE:runtime
[INFO] |  |     +- org.springframework:spring-orm:jar:3.2.9.RELEASE:runtime
[INFO] |  |     \- org.grails:grails-datastore-gorm-plugin-support:jar:3.1.4.RELEASE:runtime
[INFO] |  \- org.grails:grails-datastore-simple:jar:3.1.4.RELEASE:compile
[INFO] +- org.grails.plugins:database-migration:zip:1.4.0:runtime
[INFO] |  \- org.liquibase:liquibase-core:jar:2.0.5:runtime
[INFO] +- org.grails.plugins:jquery:zip:1.11.1:runtime
[INFO] +- org.grails.plugins:tomcat:zip:7.0.55.2:provided
[INFO] |  +- org.apache.tomcat:tomcat-catalina-ant:jar:7.0.55:provided
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-jasper:jar:7.0.55:provided
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-el:jar:7.0.55:provided
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-logging-log4j:jar:7.0.55:runtime
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-websocket:jar:7.0.55:provided
[INFO] |  +- org.eclipse.jdt.core.compiler:ecj:jar:3.7.2:provided
[INFO] |  \- org.apache.tomcat.embed:tomcat-embed-core:jar:7.0.55:provided
[INFO] \- org.grails.plugins:webxml:zip:1.4.1:runtime
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.937 s
[INFO] Finished at: 2015-06-04T12:22:52+02:00
[INFO] Final Memory: 16M/309M
[INFO] ------------------------------------------------------------------------

**Comment by rbatllet** [comment]
I've only one grails version installed with gvm 

===============================================================================
Available Grails Versions
===============================================================================
     3.0.1                2.3.5                2.1.4                1.3.4          
     3.0.0.RC3            2.3.4                2.1.3                1.3.3          
     3.0.0.RC2            2.3.3                2.1.2                1.3.2          
     3.0.0                2.3.2                2.1.1                1.3.1          
 > * 2.5.0                2.3.11               2.1.0                1.3.0          
     2.4.5                2.3.10               2.0.4                1.2.5          
     2.4.4                2.3.1                2.0.3                1.2.4          
     2.4.3                2.3.0                2.0.2                1.2.3          
     2.4.2                2.2.5                2.0.1                1.2.2          
     2.4.1                2.2.4                2.0.0                1.2.1          
     2.4.0                2.2.3                1.3.9                1.2.0          
     2.3.9                2.2.2                1.3.8                               
     2.3.8                2.2.1                1.3.7                               
     2.3.7                2.2.0                1.3.6                               
     2.3.6                2.1.5                1.3.5                               

===============================================================================
+ - local version
* - installed
> - currently in use
===============================================================================

**Comment by Kanishkaz** [comment]
Any updates on this issue?

**Comment by skufle** [comment]
I can see that the 2.4.5 version of the plugin on Github was updated to use the new Groovy version, but it's not available through the central Maven repository yet?

**Comment by bassmartin** [comment]
It would be really nice if a newer version of the plugin could be released to fix that issue. Thanks.

**Comment by graemerocher** [comment]
I have released 2.4.6 which addresses this and works with 2.5.1

It may take a little while to sync with Maven central.
